name: Node.js Package
on:
  push:
    branches:
      - 1.2.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: git config --global user.name 'ci'
    - run: git config --global user.email 'system@kailash-tech.jp'
    - working-directory: packages/vue-quill
      run: npm version patch
    - name: commit # サブディレクトリで実行する場合は npm version patch -m 使えない
      run: |
        git commit -m 'feat(vue-quill): [RELEASE]' -a
    - run: git push
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://npm.pkg.github.com'
    - run: |
        (cd packages/vue-quill; npm publish)
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
